# This is a minimal configuration file that allows the server to start
version: 7

settings:
  auto_discovery:
  - protocol_name: mqtt_ha
    device_base_topic: homeassistant/climate/
    friendly_name_subtopic: friendly_name
    last_updated_subtopic: last_updated
    on_current_temp_subtopic: current_temperature
    on_setpoint_subtopic: temperature
    on_state_subtopic: state
    on_min_temp_subtopic: min_temp
    on_max_temp_subtopic: max_temp
    set_setpoint_subtopic: new_setpoint

protocols:
  mqtt:
  - name:   "mqtt_ha"
    user:   "mqtt"       #<-- put your mqtt user name here
    pwd:    "mypasswd"   #<-- put your mqtt password here
    broker: "127.0.0.1"  #<-- mqtt broker adress :  127.0.0.1 if the heating server is installed as an home assistant integration
    port:   1884
    ssl:    false
    clean_session: true
    on_ha_status_topic: homeassistant/status

remote_control:
- name: flutter
  protocol:
    name: 'mqtt_ha'
    params:
      receive_topic: heatingcontrol/command
      send_command_response_topic: heatingcontrol/on_cmd_response
      send_devices_topic: heatingcontrol/serverdata/on_devices
      send_entities_topic: heatingcontrol/serverdata/on_entities
      send_scheduler_topic: heatingcontrol/serverdata/on_scheduler
      send_device_states_base_topic: heatingcontrol/serverdata/devices
      send_is_alive_topic: heatingcontrol/serverdata/is_alive
      is_alive_period: 5

scheduler:
  active_schedule: null
  schedules:

devices:
