devices: []
protocols:
  mqtt:
  - broker: myha.duckdns.org
    clean_session: true
    name: mqtt_ha
    port: 8884
    pwd: mypassord
    ssl: true
    user: mqtt
remote_control:
- name: flutter
  protocol:
    name: mqtt_ha
    params:
      receive_active_schedule_topic: heatingcontrol/command/set_active_schedule
      receive_delete_schedule_topic: heatingcontrol/command/delete_schedule
      receive_schedule_name_topic: heatingcontrol/command/set_schedule_name
      receive_schedule_topic: heatingcontrol/command/set_schedule
      receive_schedules_order: heatingcontrol/command/set_schedules_order
      receive_setpoint_topic: heatingcontrol/command/set_setpoint
      receive_tempset_name_topic: heatingcontrol/command/set_tempset_name
      receive_tempsets_topic: heatingcontrol/command/set_tempsets
      send_command_response_topic: heatingcontrol/command/on_response
      send_current_temp_topic: heatingcontrol/devices/$(devname)/on_current_temp
      send_devices_topic: heatingcontrol/config/on_devices
      send_scheduler_topic: heatingcontrol/config/on_scheduler
      send_setpoint_topic: heatingcontrol/devices/$(devname)/on_setpoint
      send_state_topic: heatingcontrol/devices/$(devname)/on_state
scheduler:
  active_schedule: null
  schedules: []
settings:
  message_repeater:
    repeat_delay_sec: 120
  scheduler:
    init_delay_sec: 20
