# This is a minimal configuration file that allows the server to start
version: 2

settings:
  auto_discovery:
  - protocol_name: mqtt_ha
    devices_base_topic: homeassistant/climate/
    friendly_name_subtopic: friendly_name
    on_current_temp_subtopic: current_temperature
    on_setpoint_subtopic: temperature
    on_state_subtopic: state
    set_setpoint_subtopic: new_setpoint

protocols:
  mqtt:
  - name:   "mqtt_ha"
    user:   "mqtt"
    pwd:    "mypassord"
    broker: "myha.duckdns.org"
    port:   8884
    ssl:    true
    clean_session: true

remote_control:
- name: flutter
  protocol:
    name: 'mqtt_ha'
    params:
      receive_active_schedule_topic: heatingcontrol/command/set_active_schedule
      receive_delete_schedule_topic: heatingcontrol/command/delete_schedule
      receive_schedule_name_topic: heatingcontrol/command/set_schedule_name
      receive_schedule_topic: heatingcontrol/command/set_schedule
      receive_schedules_order: heatingcontrol/command/set_schedules_order
      receive_setpoint_topic: heatingcontrol/command/set_setpoint
      receive_tempset_name_topic: heatingcontrol/command/set_tempset_name
      receive_tempsets_topic: heatingcontrol/command/set_tempsets
      send_command_response_topic: heatingcontrol/command/on_response
      send_current_temp_topic: heatingcontrol/devices/$(mqttid)/on_current_temp
      send_devices_topic: heatingcontrol/config/on_devices
      send_scheduler_topic: heatingcontrol/config/on_scheduler
      send_setpoint_topic: heatingcontrol/devices/$(mqttid)/on_setpoint
      send_state_topic: heatingcontrol/devices/$(mqttid)/on_state

scheduler:
  active_schedule: null
  schedules:

devices:
