# This is a minimal configuration file that allows the server to start
protocols:
  mqtt:
  - name:   "mqtt_ha"
    user:   "mqtt"
    pwd:    "mypassord"
    broker: "myha.duckdns.org"
    port:   8884
    ssl:    true
    clean_session: true

remote_control:
- name: flutter
  protocol:
    name: 'mqtt_ha'
    params:
      receive_schedule_topic:        'heatingcontrol/command/set_schedule'
      receive_tempsets_topic:        'heatingcontrol/command/set_tempsets'
      receive_tempset_name_topic:    'heatingcontrol/command/set_tempset_name'
      receive_schedule_name_topic:   'heatingcontrol/command/set_schedule_name'
      receive_delete_schedule_topic: 'heatingcontrol/command/delete_schedule'
      receive_active_schedule_topic: 'heatingcontrol/command/set_active_schedule'
      receive_setpoint_topic:        'heatingcontrol/command/set_setpoint'
      send_command_response_topic:   'heatingcontrol/command/on_response'
      send_scheduler_topic:          'heatingcontrol/config/on_scheduler'
      send_devices_topic:            'heatingcontrol/config/on_devices'
      send_current_temp_topic:       'heatingcontrol/devices/$(devname)/on_current_temp'
      send_setpoint_topic:           'heatingcontrol/devices/$(devname)/on_setpoint'

scheduler:
  schedules:

devices: