# see https://docs.python.org/3/library/logging.config.html
# and https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    # see https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler
    class: logging.handlers.RotatingFileHandler
    mode: w
    level: DEBUG
    formatter: simple
    filename: /config/heating_ctrl_srv.log
    maxBytes: 10485760 # 10MB
    backupCount: 2
    encoding: utf8
loggers:
  hcs:
    level: INFO
    handlers: [file_handler]
    propagate: no
#root:
#  level: DEBUG
#  handlers: [file_handler]