mqtt_statestream:
  ####################################################
  # Heating Control server
  # AUTO PUBLISH ANY CLIMATE ENTITIES TO MQTT BROKER 
  ####################################################
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: false
  include:
    domains:
      - climate
    entity_globs:
      - climate.*

heating_control_srv:
  ####################################################
  # Enable Heating Control server custom component
  ####################################################
