####################################################
# Heating Control server
# AUTO PUBLISH ANY CLIMATE ENTITIES TO MQTT BROKER 
####################################################
mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: false
  include:
    domains:
      - climate
    entity_globs:
      - climate.*

####################################################
# Enable Heating Control server custom component
####################################################
heating_control_srv:
  
