mqtt_statestream:
  ####################################################
  # Heating Control server
  # AUTO PUBLISH ANY CLIMATE ENTITIES TO MQTT BROKER 
  ####################################################
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
  include:
    domains:
      - climate
    entity_globs:
      - climate.*
